---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    backstage.io/kubernetes-id: mywebsite
    app.kubernetes.io/name: mywebsite
    rht-gitops.com/janus-argocd: mywebsite
  name: storeuser-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    backstage.io/kubernetes-id: mywebsite
    app.kubernetes.io/name: mywebsite
    rht-gitops.com/janus-argocd: mywebsite
  name: storeuseradmin-sa
