---
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: mywebsite-scc-storeuser
  labels:
    backstage.io/kubernetes-id: mywebsite
    app.kubernetes.io/name: mywebsite
    rht-gitops.com/janus-argocd: mywebsite
allowHostPID: false
allowHostNetwork: false
allowPrivilegeEscalation: true
allowHostDirVolumePlugin: false
allowHostIPC: false
readOnlyRootFilesystem: false
allowHostPorts: false
allowPrivilegedContainer: false
runAsUser:
  type: MustRunAs
  uid: 10001
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:mywebsite-marghe:storeuser-sa
---
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: mywebsite-scc-storeuseradmin
  annotations:
    backstage.io/kubernetes-id: mywebsite
allowHostPID: false
allowHostNetwork: false
allowPrivilegeEscalation: true
allowHostDirVolumePlugin: false
allowHostIPC: false
readOnlyRootFilesystem: false
allowHostPorts: false
allowPrivilegedContainer: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:mywebsite-marghe:storeuseradmin-sa
